### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bootstraponline** [bootstraponline/angular_webdriver#29]
- [x] Complete milestone 0.8
- [x] Add `element` to page-object that doesn't require tag_name, (tag_name will change and shouldn't be breaking tests).
- [x] Add protractor locators to page-object
- [x] Update sauce_connect_ruby example

**Comment by bootstraponline** [comment]
complete
